include "../sfbay-pilates-base.conf"

beam.agentsim.simulationName = "sfbay-pilates-base--jdeq"
beam.agentsim.agentSampleSizeAsFractionOfPopulation = 1.0
beam.agentsim.lastIteration = 12
beam.agentsim.agents.freight.enabled = false

beam.physsim.name = "JDEQSim"
beam.physsim.flowCapacityFactor = 1.0
beam.physsim.storageCapacityFactor = 1.0
beam.physsim.skipPhysSim = false
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/r5-simple-no-local/physsim-network.xml"
#beam.physsim.overwriteLinkParamPath = ${beam.inputDirectory}"/r5/r5-simple-no-local/updatedLinkParams.csv"

beam.routing.r5.directory = ${beam.inputDirectory}"/r5/r5-simple-no-local"
beam.routing.r5.osmMapdbFile = ${beam.inputDirectory}"/r5/r5-simple-no-local/osm.mapdb"
#beam.routing.r5.directory2 = ${beam.inputDirectory}"/r5/r5-simple-no-local-no-buses"

beam.warmStart.initialLinkstatsFilePath = ""
beam.warmStart.prepareData = true




