include "sfbay-base.conf"

beam.agentsim.simulationName = "sfbay-pilates-base"

beam.inputDirectory = ${PWD}"/input/sfbay"

# Ingest 275000 households -> 720000 persons from activitysim
beam.agentsim.agentSampleSizeAsFractionOfPopulation = 1.0
beam.agentsim.firstIteration = 0
beam.agentsim.lastIteration = 2
#merging incoming input with the lat run output
beam.agentsim.agents.plans.merge.fraction = 0.4

beam.input.lastBaseOutputDir = ${beam.outputs.baseOutputDirectory}
beam.input.simulationPrefix = "year"
beam.outputs.defaultWriteInterval=1
beam.router.skim.writeSkimsInterval=1
beam.exchange.output.activity-sim-skimmer.primary.enabled = true

beam.physsim.skipPhysSim = false
beam.physsim.eventsForFullVersionOfVia = false
beam.physsim.flowCapacityFactor = 0.105
beam.physsim.storageCapacityFactor = 1.0
beam.physsim.name = "JDEQSim"
beam.routing.r5.travelTimeNoiseFraction = 0.05


beam.warmStart.type = "linkStatsFromLastRun"
# beam.warmStart.initialLinkstatsFilePath = ${beam.inputDirectory}"/r5/sfbay-area-cbg5500-weakConn-network/3.linkstats.csv.gz"

beam.exchange.scenario {
  modeMap = [
    "BIKE           -> bike",
    "DRIVEALONEFREE -> car",
    "DRIVEALONEPAY  -> car",
    "DRIVE_COM      -> drive_transit",
    "DRIVE_EXP      -> drive_transit",
    "DRIVE_HVY      -> drive_transit",
    "DRIVE_LOC      -> drive_transit",
    "DRIVE_LRF      -> drive_transit",
    "SHARED2FREE    -> car_hov2",
    "SHARED2PAY     -> car_hov2",
    "SHARED3FREE    -> car_hov3",
    "SHARED3PAY     -> car_hov3",
    "TAXI           -> ride_hail",
    "TNC_SHARED     -> ride_hail_pooled",
    "TNC_SINGLE     -> ride_hail",
    "WALK           -> walk",
    "WALK_COM       -> walk_transit",
    "WALK_EXP       -> walk_transit",
    "WALK_HVY       -> walk_transit",
    "WALK_LOC       -> walk_transit",
    "WALK_LRF       -> walk_transit",
  ]
}