include "sfbay-pilates-base.conf"

beam.agentsim.simulationName = "sfbay-pilates-base-zarr"
# Ingest 275000 households -> 720000 persons from activitysim


beam.router.skim.activity-sim-skimmer.fileOutputFormat = "zarr"

beam.exchange.scenario.fileFormat = "parquet"
beam.outputs.events.fileOutputFormats = "parquet"

beam.agentsim.agents.vehicles.vehicleTypesFilePath = ${beam.inputDirectory}"/atlas-vehicles/vehicleTypes_baseline.csv"
beam.agentsim.agents.vehicles.vehiclesFilePath = ${beam.exchange.scenario.folder}"/vehicles.csv.gz"
