include "../../sfbay-pilates-base.conf"

beam.agentsim.simulationName = "sfbay-beam-network--psimpl-sfres-jdeq"
beam.agentsim.agentSampleSizeAsFractionOfPopulation = 0.1
beam.agentsim.lastIteration = 12
beam.agentsim.agents.freight.enabled = false

beam.physsim.name = "JDEQSim"
beam.physsim.flowCapacityFactor = 1.0
beam.physsim.storageCapacityFactor = 1.0
beam.physsim.skipPhysSim = false
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/sfbay-cbg5500-weakConn-network/physsim-network.xml"
#beam.physsim.overwriteLinkParamPath = ${beam.inputDirectory}"/r5/sfbay-cbg5500-weakConn-network/updatedLinkParams.csv"

beam.routing.r5.directory = ${beam.inputDirectory}"/r5/sfbay-cbg5500-weakConn-network"
beam.routing.r5.osmMapdbFile = ${beam.inputDirectory}"/r5/sfbay-cbg5500-weakConn-network/osm.mapdb"
#beam.routing.r5.directory2 = ${beam.inputDirectory}"/r5/sfbay-cbg5500-weakConn-network-no-buses"

beam.warmStart.initialLinkstatsFilePath = ""
beam.warmStart.prepareData = true