include "../../sfbay-pilates-base.conf"

beam.agentsim.simulationName = "beam-pilates-run--sfbay--jdeq-calibration"
beam.agentsim.agentSampleSizeAsFractionOfPopulation = 0.1
beam.agentsim.lastIteration = 0

beam.warmStart.type = ""
beam.warmStart.path = ""
beam.warmStart.initialLinkstatsFilePath = ""
beam.warmStart.prepareData = true

beam.physsim.flowCapacityFactor = 0.09
#beam.physsim.storageCapacityFactor = 0.5
beam.physsim.storageCapacityFactor = 1.0
beam.physsim.name = "JDEQSim"

# The following parameters control the number of lanes in short links, which is the primary method to manage storage capacity in links in beam.
# The override is activated when minimumLinkLengthThreshold is greater than 0.
beam.physsim.jdeqsim.shortLink.storageCapacityOverride {
    minimumLinkLengthThreshold = 10.0  # Minimum length threshold (greater than 0) to activate lane override.
    overriddenNumLanesPerLink = 50.0  # Number of lanes to use when overriding the default configuration for short links.
}