include "beam-pilates-run--sfbay--jdeq-calibration.conf"

beam.agentsim.simulationName = "beam-pilates-run--sfbay--jdeq-calibration-FC06-0"

beam.agentsim.lastIteration = 6
beam.physsim.flowCapacityFactor = 0.06
beam.physsim.relaxation.type = "experiment_2.1"
beam.physsim.relaxation.experiment2_1.internalNumberOfIterations = 50
beam.physsim.relaxation.experiment2_1.fractionOfPopulationToReroute = 0.1
beam.physsim.relaxation.experiment2_1.clearRoutesEveryIteration = true
beam.physsim.relaxation.experiment2_1.clearModesEveryIteration = false
beam.routing.r5.travelTimeNoiseFraction = 0.1

beam.warmStart.type = "linkStatsOnly"
beam.warmStart.initialLinkstatsFilePath = ${beam.inputDirectory}"/r5/sfbay-cbg5500-weakConn-network/2018-baseline-linkstats/3.linkstats.FC06.v1.csv.gz"

#beam.physsim.jdeqsim.shortLink.storageCapacityOverride {
#    minimumLinkLengthThreshold = 10.0  # Minimum length threshold (greater than 0) to activate lane override.
#    overriddenNumLanesPerLink = 10.0  # Number of lanes to use when overriding the default configuration for short links.
#}