include "../../sfbay-base.conf"

beam.agentsim.simulationName = "sfbay-base--psimpl-sfres-network-jdeq-05-cbg"
beam.agentsim.agentSampleSizeAsFractionOfPopulation = 0.1
beam.agentsim.lastIteration = 0

beam.warmStart.type = "disabled"
beam.warmStart.prepareData = false

beam.physsim.flowCapacityFactor = 0.05
#beam.physsim.storageCapacityFactor = 0.5
beam.physsim.storageCapacityFactor = 1.0
beam.physsim.name = "JDEQSim"
beam.physsim.overwriteLinkParamPath = ${beam.inputDirectory}"/r5/r5-partially-simplified-sfres/updatedLinkParams.csv"
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/r5-partially-simplified-sfres/physsim-network.xml"

beam.routing.r5.directory = ${beam.inputDirectory}"/r5/r5-partially-simplified-sfres"
beam.routing.r5.osmMapdbFile = ${beam.inputDirectory}"/r5/r5-partially-simplified-sfres/osm.mapdb"
beam.routing.r5.directory2 = ${beam.inputDirectory}"/r5/r5-partially-simplified-sfres-no-buses"

beam.exchange.output {
   activitySimSkimsEnabled = true
   sendNonChosenTripsToSkimmer = true
   geo {
        filePath = ${beam.inputDirectory}"/shape/sfbay_cbgs_epsg26910.geojson"
        geoIdFieldName = "GEOID"
        geoId2TazIdMapFilePath = ${beam.inputDirectory}"/shape/sfbay_cbg_taz_map.csv"
        beamModeFilter = ["car"]
   }
}

beam.exchange.output.secondary-activity-sim-skimmer {
   enabled = true
   # To filter the modes in the mapped skim using beam mode schema
   beamModeFilter = [
    "car"
   ]
   # geo level different than beam.agentsim.taz format
   secondaryTazFilePath = ${beam.inputDirectory}"/shape/sfbay_cbgs_epsg26910.geojson"
   secondaryTazIdFieldName = "GEOID"
   geoZoneMapping {
       # To map this geo level with beam.agentsim.taz using two columns CSV file
       # One of the column name should be the value of geoIdFieldName
       # The other column name should be the value of beam.agentsim.taz.tazIdFieldName
       # If left empty, BEAM will automatically map beam.agentsim.taz to this zone system
       filePath = ${beam.inputDirectory}"/shape/sfbay_cbg_taz_map.csv"
       geoIdFieldNameKey = "GEOID"
       geoIdFieldNameValue = "taz1454"
   }
}

beam.physsim.linkStatsWriteInterval = 1
beam.physsim.writeEventsInterval = 1
beam.physsim.writePlansInterval = 1
beam.physsim.writeRouteHistoryInterval = 0

beam.outputs.defaultWriteInterval = 1
beam.outputs.writePlansInterval = 1
beam.outputs.writeEventsInterval = 1

beam.router.skim.writeAggregatedSkimsInterval = 1
beam.router.skim.writeSkimsInterval = 1
beam.router.skim.origin-destination-skimmer.writeFullSkimsInterval = 0
beam.router.skim.activity-sim-skimmer.fileOutputFormat = "omx"






